### ISSUE TITLE
ngw build - don't work

### ISSUE THREAD

**Issue by eugenotop** [Angular-RU/angular-cli-webpack#39]
project$ yarn build
yarn run v1.10.1
$ ngw build
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/util/subscribeTo.ts:37:11)
    at Object.subscribeToResult (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/util/subscribeToResult.ts:18:10)
    at MergeMapSubscriber._innerSub (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/operators/mergeMap.ts:142:14)
    at MergeMapSubscriber._tryNext (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/operators/mergeMap.ts:138:10)
    at MergeMapSubscriber._next (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/operators/mergeMap.ts:122:12)
    at MergeMapSubscriber.Subscriber.next (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/Subscriber.ts:102:12)
    at MapSubscriber._next (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/operators/map.ts:86:22)
    at MapSubscriber.Subscriber.next (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/Subscriber.ts:102:12)
    at Observable._subscribe (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/observable/scalar.ts:5:16)
    at Observable._trySubscribe (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/Observable.ts:223:19)
    at Observable.subscribe (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/Observable.ts:204:14)
    at MapOperator.call (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/operators/map.ts:56:19)
    at Observable.subscribe (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/Observable.ts:199:16)
    at MergeMapOperator.call (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/operators/mergeMap.ts:97:19)
    at Observable.subscribe (project/node_modules/@angular-devkit/core/node_modules/rxjs/src/internal/Observable.ts:199:16)
    at MergeMapOperator.call (project/node_modules/@angular/cli/node_modules/rxjs/src/internal/operators/mergeMap.ts:97:19)
child_process.js:645
    throw err;
    ^

Error: Command failed: node "project/node_modules/ngw/node_modules/ts-node/dist/bin.js" "project/node_modules/ngw/lib/index.js" "build"
    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
    at Object.<anonymous> (project/node_modules/ngw/bin/ngw:14:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
error Command failed with exit code 1.

//// ngw.config.ts
import * as webpack from 'webpack';
import { Path } from '@angular-devkit/core';
import { NormalizedBrowserBuilderSchema } from '@angular-devkit/build-angular';

// tslint:disable-next-line:interface-over-type-literal
export type WebpackOptions<T = NormalizedBrowserBuilderSchema> = {
    root: Path,
    projectRoot: Path,
    options: T;
};

const command = process.argv[2].toLowerCase();

export default function (config: webpack.Configuration, options: WebpackOptions) {
    if (command === 'test') {
            console.log('Test configuration is running');
    }
    console.log('To modify webpack build, you can use ngw.config.ts');
    return config;
}

//// package.json

"dependencies": {
    "@angular/animations": "^6.1.9",
    "@angular/common": "^6.1.9",
    "@angular/compiler": "^6.1.9",
    "@angular/core": "^6.1.9",
    "@angular/forms": "^6.1.9",
    "@angular/http": "^6.1.9",
    "@angular/platform-browser": "^6.1.9",
    "@angular/platform-browser-dynamic": "^6.1.9",
    "@angular/router": "^6.1.9",
    "@ngrx/effects": "6.1.0",
    "@ngrx/router-store": "6.1.0",
    "@ngrx/store": "6.1.0",
    "@nguniversal/express-engine": "^6.1.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.1.0",
    "@nrwl/nx": "6.4.0",
    "@nrwl/schematics": "^6.3.1",
    "body-parser": "^1.18.3",
    "buffer": "^5.2.1",
    "core-js": "^2.5.4",
    "http-proxy-middleware": "^0.19.0",
    "memory-cache": "^0.2.0",
    "mime-types": "^2.1.20",
    "request": "^2.88.0",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^2.5.4",
    "@angular-devkit/build-angular": "^0.8.4",
    "@angular/cli": "^6.1.5",
    "@angular/compiler-cli": "^6.1.9",
    "@angular/language-service": "^6.1.9",
    "@angular/platform-server": "^6.1.9",
    "@ngrx/store-devtools": "6.1.0",
    "@storybook/addon-actions": "^3.4.11",
    "@storybook/addon-links": "^3.4.11",
    "@storybook/addon-notes": "^3.4.11",
    "@storybook/addons": "^3.4.11",
    "@storybook/angular": "^3.4.11",
    "@types/body-parser": "^1.17.0",
    "@types/compression": "^0.0.36",
    "@types/cookie-parser": "^1.4.1",
    "@types/express": "^4.16.0",
    "@types/express-serve-static-core": "^4.16.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/memory-cache": "^0.2.0",
    "@types/mime-types": "^2.1.0",
    "@types/morgan": "^1.7.35",
    "@types/serve-static": "^1.13.2",
    "@types/webfontloader": "^1.6.29",
    "@types/webpack": "^4.4.16",
    "accepts": "^1.3.5",
    "angular-svg-icon": "^6.0.0",
    "babel-core": "^6.26.3",
    "codelyzer": "~4.5.0",
    "cookie-parser": "^1.4.3",
    "css-loader": "^1.0.0",
    "express": "^4.16.3",
    "html-webpack-plugin": "^3.2.0",
    "jasmine-core": "~3.2.1",
    "jasmine-marbles": "0.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "json-loader": "^0.5.7",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "less": "^3.8.1",
    "moment": "^2.22.2",
    "morgan": "^1.9.1",
    "ngrx-store-freeze": "0.2.4",
    "ngw": "^6.1.0",
    "nodemon": "^1.18.4",
    "preboot": "^6.0.0-beta.5",
    "prettier": "1.14.3",
    "protractor": "~5.4.0",
    "raw-loader": "^0.5.1",
    "safe-memory-cache": "^1.5.1",
    "script-ext-html-webpack-plugin": "^2.0.1",
    "swagger-ui-express": "^4.0.1",
    "tiny": "^0.0.10",
    "ts-loader": "^5.2.1",
    "ts-node": "^7.0.1",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "tslint": "~5.11.0",
    "typescript": "2.9.2",
    "webpack-cli": "^3.1.2"
  }

**Comment by ivanpadavan** [comment]
Yeah. it's a known issue. You can switch to @angular-devkit/build-angular: ~0.7
https://github.com/Angular-RU/angular-cli-webpack/issues/35#issuecomment-423720273

**Comment by eugenotop** [comment]
this is don't work for me #35 (comment)

**Comment by domi7777** [comment]
I had the same issue, I figured my angular & angular-cli dependencies didn't have the same version as ngw. After I changed it, it built correctly (I enforced specific version 6.0.7 by removing the ^)

**Comment by ivanpadavan** [comment]
It's not intended to sync precisely versions if ngw and angular. But thank
you for the clue! Cannot undestand what causes this issue

вт, 23 окт. 2018 г., 14:54 domi <notifications@github.com>:
